[package]
name = "fcfm-documents"
version = "100.0.0"
entrypoint = "conf.typ"
authors = ["Esteban Muñoz"]
license = "MIT-0"
description = "Reports, assignments and auxiliary classes template to use in FCFM."
exclude = [".git", ".gitignore"]

[template]
path = "template"
entrypoint = "main.typ"
